name: Vitor Fraga
bio: Data Analyst
description: Data Analyst
external-image: false
picture: assets/images/profile.jpg
resume: true
resume-external: true
resume-url: 'https://google.com/?q=my+resume'
url: 'https://koppl.in/indigo'
permalink: '/:title/'
disqus:
  shortname: mydisqus
  categories:
    - blog
    - project
# facebook: myfacebook
# twitter: mytwitter
github: vitorfraga
medium: false
email: vitor.augusto.fraga@gmail.com
linkedin: vitorfraga
authors:
  johndoe:
    name: Vitor Fraga
    bio: Data Analyst
    external-image: false
    picture: assets/images/profile.jpg
    twitter: false
 
width: normal
pagination:
  enabled: false
  sort_reverse: true
  title: ':title'
  per_page: 5
  permalink: '/:num/'
projects: false
about: true
blog: false
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
defaults:
  - scope:
      path: ''
      layout: post
    values:
      hidden: false
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate-v2
  - jekyll-fontawesome-svg
jekyll-mentions:
  base_url: 'https://github.com'
compress_html:
  ignore:
    envs:
      - development
      - stage
exclude:
  - travis.sh
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
  - node_modules
  - vendor
